### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by ghanavat** [damieng/jekyll-blog-comments#8]
Hey Damien,
I have noticed that the comments are sorted by date in ascending order and I think it's a default. I have added `reverse` to `{% assign sorted_comments = comments | sort: 'date' | reverse %}` in _comments.html_.
I think it'd make more sense to order the comments by date in descending order, so the new comments appear to the top. 

Please let me know your thoughts. If you agree, you can amend the file, therefore it'd be already done for new users of your solution.

**Comment by damieng** [comment]
I personally prefer the current accessing order at least until threading is implemented. Otherwise you are reading replies before what they are replying to.

**Comment by ghanavat** [comment]
Done a quick research, I think it's correct that visitors read the oldest comments first, so they don't have scroll up and down all the time, as it'd make them swtich between posts all the time. You have mentioned 'threading'. Are you working on it?

**Comment by damieng** [comment]
I haven't made a start on it but it would involve:

1. Each comment having a parent_id front-matter field (optional, if missing it's a top level)
2. Comments template would be capable of correctly ordering them so that replies are in the right sequence in the right context.
3. Comments template capable of rendering the replies at least with 1 level of nesting and providing a "reply" link that would copy the new-comment form from elsewhere on the page inline to below where the parent comment is filling in the optional hidden parent_id field.
4. The form receiver capable of receiving the parent_id field and storing this in the db (easiest to do, different repo I can easily add ahead of time)

I think visually it would be okay to only show one level of nesting even for replies to replies but with some indication above each comment as to who/what it is a reply-to.

**Comment by ghanavat** [comment]
I agree with one level of nesting. I think it would keep the threading neat and tidy.

The point 4 above, I don't understand it when you saying `I can easily add ahead of time`? What do you mean? Correct me if I'm wrong, you mean AOT compilation?

**Comment by damieng** [comment]
Oh, I just mean I can make the code change for 4 right now - it lives in a different repo and would be backward compatible.

**Comment by ghanavat** [comment]
Excellent. My bad. I think my brain was too much forward thinking. I think it'd be great Damien to implement the threading. It seems like that you know exactly what needs to be done.

**Comment by ghanavat** [comment]
Hey Damian, any update on the threading you were going to work on? I am going to think about a way to hide the email field from the comment yml file and store it differently; and I thought I ask you about the threading too.

**Comment by damieng** [comment]
I've not had any free time to work on this so there's nothing to report back at this time.
